
FROM openjdk:17-jdk-alpine

WORKDIR /app

COPY build.gradle settings.gradle gradlew /app/
COPY gradle /app/gradle

RUN ./gradlew dependencies --no-daemon

COPY src /app/src

RUN ./gradlew bootJar --no-daemon

COPY build/libs/challenge-0.0.1-SNAPSHOT.jar /app/challenge.jar

EXPOSE 8080

ENTRYPOINT ["java", "-jar", "challenge.jar"]
